package _default

const (
	ENV_CORE_HOST_STR = "CORE_HOST"
	ENV_CORE_PORT_STR = "CORE_PORT"

	ENV_CORE_AUTH_PROVIDE       = "AUTH_PROVIDER"
	ENV_CORE_AUTH_ENDPOINT      = "AUTH_ENDPOINT"
	ENV_CORE_AUTH_CLIENT_ID     = "AUTH_CLIENT_ID"
	ENV_CORE_AUTH_CLIENT_SECRET = "AUTH_CLIENT_SECRET"
	ENV_CORE_AUTH_ORGANIZATION  = "AUTH_ORGANIZATION"
	ENV_CORE_AUTH_PUBLICKEYFILE = "AUTH_PUBLICKEYFILE"
)
