version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: sunday
      timezone: "Asia/Shanghai"
  - package-ecosystem: "pip"
    directory: "/test/mock_driver/clock"
    schedule:
      interval: "monthly"
      day: 1
      timezone: "Asia/Shanghai"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      timezone: "Asia/Shanghai"
