DROP DATABASE IF EXISTS lubricant;
CREATE DATABASE lubricant;
GRANT ALL PRIVILEGES ON lubricant.* TO 'lubricant'@'%';

DROP DATABASE IF EXISTS casdoor;
CREATE DATABASE casdoor;
CREATE USER 'casdoor'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON casdoor.* TO 'casdoor'@'%';
FLUSH PRIVILEGES;
