CREATE DATABASE lubricant;
CREATE USER 'lubricant'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON lubricant.* TO 'lubricant'@'%';

CREATE DATABASE casdoor;
CREATE USER 'casdoor'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON casdoor.* TO 'casdoor'@'%';
FLUSH PRIVILEGES;
