apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubricant-grpcserver
  namespace: lubricant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lubricant-grpcserver
  template:
    metadata:
      labels:
        app: lubricant-grpcserver
    spec:
      containers:
        - name: lubricant-grpcserver
          image: hub.iotroom.top/aenjoy/lubricant-grpcserver:nightly
          ports:
            - containerPort: 5423
              name: grpc
              protocol: TCP
          env:
            - name: GRPC_LISTEN_PORT
              value: "5423"
            - name: DB_USER
              value: "lubricant"
            - name: DB_ADDRESS
              value: "mysql.database.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "lubricant"
            - name: RUNNING_LEVEL
              value: "debug"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lubricant-secrets
                  key: DB_PASSWORD
            - name: REDIS_ENABLE
              value: "true"
            - name: REDIS_HOST
              value: "redis.database.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lubricant-secrets
                  key: redis-password
            - name: REDIS_DB
              value: "0"
            - name: MQ_TYPE
              value: "nats"
            - name: NATS_URL
              value: "nats://nats.database.svc.cluster.local:4222"
            - name: SVC_DATASTORE_ENDPOINT
              value: datastore.lubricant.svc.cluster.local:5423
            - name: SVC_DATASTORE_MODE
              value: mq # mq or rpc
---
apiVersion: v1
kind: Service
metadata:
  name: lubricant-grpcserver
  namespace: lubricant
spec:
  type: NodePort
  ports:
    - port: 5423
      name: grpc
      targetPort: 5423
  selector:
    app: lubricant-grpcserver
