apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubricant-report
  namespace: lubricant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lubricant-report
  template:
    metadata:
      labels:
        app: lubricant-report
    spec:
      containers:
        - name: lubricant-report
          image: hub.iotroom.top/aenjoy/lubricant-report:nightly
          env:
            - name: DB_USER
              value: "lubricant"
            - name: DB_ADDRESS
              value: "mysql.database.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "lubricant"
            - name: RUNNING_LEVEL
              value: "debug"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lubricant-secrets
                  key: DB_PASSWORD
            - name: MQ_TYPE
              value: "nats"
            - name: NATS_URL
              value: "nats://nats.database.svc.cluster.local:4222"
