apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubricant-core-logger
  namespace: lubricant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lubricant-core-logger
  template:
    metadata:
      labels:
        app: lubricant-core-logger
    spec:
      containers:
        - name: lubricant-core-logger
          image: hub.iotroom.top/aenjoy/lubricant-core-logger:nightly
          env:
            - name: DB_USER
              value: "lubricant"
            - name: DB_ADDRESS
              value: "mysql.database.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "lubricant"
            - name: RUNNING_LEVEL
              value: "debug"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lubricant-secrets
                  key: DB_PASSWORD
            - name: REDIS_ENABLE
              value: "true"
            - name: REDIS_HOST
              value: "redis.database.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lubricant-secrets
                  key: redis-password
            - name: REDIS_DB
              value: "0"
            - name: MQ_TYPE
              value: "nats"
            - name: NATS_URL
              value: "nats://nats.database.svc.cluster.local:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: lubricant-core-logger
  namespace: lubricant
spec:
  selector:
    app: lubricant-core-logger
