apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubricant-datastore
  namespace: lubricant
spec:
  replicas: 5 # Number of replicas for the datastore deployment should be >= 4
  selector:
    matchLabels:
      app: lubricant-datastore
  template:
    metadata:
      labels:
        app: lubricant-datastore
    spec:
      containers:
        - name: lubricant-datastore
          image: hub.iotroom.top/aenjoy/lubricant-datastore:nightly
          env:
            - name: RUNNING_LEVEL
              value: "debug"
            - name: DB_USER
              value: "lubricant"
            - name: DB_ADDRESS
              value: "mysql.database.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "lubricant"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lubricant-secrets
                  key: DB_PASSWORD
            - name: REDIS_ENABLE
              value: "true"
            - name: REDIS_HOST
              value: "redis.database.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lubricant-secrets
                  key: redis-password
            - name: REDIS_DB
              value: "0"
            - name: MQ_TYPE
              value: "nats"
            - name: NATS_URL
              value: "nats://nats.database.svc.cluster.local:4222"
            - name: ETCD_ENDPOINTS
              value: "etcd.database.svc.cluster.local:2379"
            - name: INTERNAL_WORK_THREAD_NUMBER
              value: "2048"
