// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: protobuf/core/data.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int32 `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"` // 0:Ping 1:Pong 3: Error
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_core_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_core_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_protobuf_core_data_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	MessageId string `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"` // 如果服务端任务该消息需要处理,则会返回预响应的messageID;否则getTask req.messageId应该与返回的resp.messageId一致
	Content   []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`     // json格式 []byte
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_core_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_core_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_protobuf_core_data_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Task) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type MessageIdInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"` // 如果服务端任务该消息需要处理,则会返回预响应的messageID;pushMessageId req.messageId应该与返回的resp.messageId一致
	GatewayId string `protobuf:"bytes,2,opt,name=gatewayId,proto3" json:"gatewayId,omitempty"`
	Time      string `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Emergency string `protobuf:"bytes,4,opt,name=emergency,proto3" json:"emergency,omitempty"` // 0: 不需要立即回应 1: 需要立即回应(将直接返回resp的消息ID)
	Content   []byte `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`     // json格式 []byte 响应内容resp
}

func (x *MessageIdInfo) Reset() {
	*x = MessageIdInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_core_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageIdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageIdInfo) ProtoMessage() {}

func (x *MessageIdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_core_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageIdInfo.ProtoReflect.Descriptor instead.
func (*MessageIdInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_core_data_proto_rawDescGZIP(), []int{2}
}

func (x *MessageIdInfo) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageIdInfo) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *MessageIdInfo) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *MessageIdInfo) GetEmergency() string {
	if x != nil {
		return x.Emergency
	}
	return ""
}

func (x *MessageIdInfo) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string   `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"` //如果messageId不符合uuid,则认为是返回错误信息
	GatewayId string   `protobuf:"bytes,2,opt,name=gatewayId,proto3" json:"gatewayId,omitempty"`
	AgentID   string   `protobuf:"bytes,3,opt,name=agentID,proto3" json:"agentID,omitempty"` // agentID用于标记数据所属
	Data      [][]byte `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`       // 二进制数据字段
	DataLen   int32    `protobuf:"varint,5,opt,name=dataLen,proto3" json:"dataLen,omitempty"`
	Time      string   `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`   // 起始时间
	Cycle     string   `protobuf:"bytes,7,opt,name=cycle,proto3" json:"cycle,omitempty"` // 数据周期
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_core_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_core_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_protobuf_core_data_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Data) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *Data) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *Data) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Data) GetDataLen() int32 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

func (x *Data) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Data) GetCycle() string {
	if x != nil {
		return x.Cycle
	}
	return ""
}

var File_protobuf_core_data_proto protoreflect.FileDescriptor

var file_protobuf_core_data_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x75, 0x62, 0x72,
	0x69, 0x63, 0x61, 0x6e, 0x74, 0x22, 0x1a, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6c, 0x61,
	0x67, 0x22, 0x56, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x97, 0x01, 0x0a, 0x0d, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x32, 0xeb, 0x01, 0x0a, 0x0b, 0x63,
	0x6f, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x70, 0x69,
	0x6e, 0x67, 0x12, 0x0f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x1a, 0x0f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x07, 0x67, 0x65,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e,
	0x74, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x0f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61,
	0x6e, 0x74, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x45, 0x0a,
	0x0d, 0x70, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x18, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69,
	0x63, 0x61, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x70, 0x75, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x0f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x0f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protobuf_core_data_proto_rawDescOnce sync.Once
	file_protobuf_core_data_proto_rawDescData = file_protobuf_core_data_proto_rawDesc
)

func file_protobuf_core_data_proto_rawDescGZIP() []byte {
	file_protobuf_core_data_proto_rawDescOnce.Do(func() {
		file_protobuf_core_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_core_data_proto_rawDescData)
	})
	return file_protobuf_core_data_proto_rawDescData
}

var file_protobuf_core_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_core_data_proto_goTypes = []any{
	(*Ping)(nil),          // 0: lubricant.Ping
	(*Task)(nil),          // 1: lubricant.Task
	(*MessageIdInfo)(nil), // 2: lubricant.MessageIdInfo
	(*Data)(nil),          // 3: lubricant.Data
}
var file_protobuf_core_data_proto_depIdxs = []int32{
	0, // 0: lubricant.coreService.ping:input_type -> lubricant.Ping
	1, // 1: lubricant.coreService.getTask:input_type -> lubricant.Task
	2, // 2: lubricant.coreService.pushMessageId:input_type -> lubricant.MessageIdInfo
	3, // 3: lubricant.coreService.pushData:input_type -> lubricant.Data
	0, // 4: lubricant.coreService.ping:output_type -> lubricant.Ping
	1, // 5: lubricant.coreService.getTask:output_type -> lubricant.Task
	2, // 6: lubricant.coreService.pushMessageId:output_type -> lubricant.MessageIdInfo
	3, // 7: lubricant.coreService.pushData:output_type -> lubricant.Data
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_core_data_proto_init() }
func file_protobuf_core_data_proto_init() {
	if File_protobuf_core_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_core_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_core_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_core_data_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MessageIdInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_core_data_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_core_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_core_data_proto_goTypes,
		DependencyIndexes: file_protobuf_core_data_proto_depIdxs,
		MessageInfos:      file_protobuf_core_data_proto_msgTypes,
	}.Build()
	File_protobuf_core_data_proto = out.File
	file_protobuf_core_data_proto_rawDesc = nil
	file_protobuf_core_data_proto_goTypes = nil
	file_protobuf_core_data_proto_depIdxs = nil
}
