// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: protobuf/gateway/api_agent.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	agent "github.com/aenjoy/iot-lubricant/protobuf/agent"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       []string               `protobuf:"bytes,1,rep,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAgentRequest) Reset() {
	*x = StartAgentRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAgentRequest) ProtoMessage() {}

func (x *StartAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAgentRequest.ProtoReflect.Descriptor instead.
func (*StartAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{0}
}

func (x *StartAgentRequest) GetAgentId() []string {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type StopAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       []string               `protobuf:"bytes,1,rep,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAgentRequest) Reset() {
	*x = StopAgentRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentRequest) ProtoMessage() {}

func (x *StopAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentRequest.ProtoReflect.Descriptor instead.
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StopAgentRequest) GetAgentId() []string {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type RemoveAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       []string               `protobuf:"bytes,1,rep,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentRequest) Reset() {
	*x = RemoveAgentRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentRequest) ProtoMessage() {}

func (x *RemoveAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentRequest.ProtoReflect.Descriptor instead.
func (*RemoveAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveAgentRequest) GetAgentId() []string {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type UpdateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Conf          []byte                 `protobuf:"bytes,2,opt,name=conf,proto3,oneof" json:"conf,omitempty"` //agentCreate config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateAgentRequest) GetConf() []byte {
	if x != nil {
		return x.Conf
	}
	return nil
}

type EditAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Info          *agent.AgentInfo       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Conf          []byte                 `protobuf:"bytes,3,opt,name=conf,proto3,oneof" json:"conf,omitempty"` // CreateAgentRequest config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAgentRequest) Reset() {
	*x = EditAgentRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAgentRequest) ProtoMessage() {}

func (x *EditAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAgentRequest.ProtoReflect.Descriptor instead.
func (*EditAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{4}
}

func (x *EditAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EditAgentRequest) GetInfo() *agent.AgentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *EditAgentRequest) GetConf() []byte {
	if x != nil {
		return x.Conf
	}
	return nil
}

type CreateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *agent.AgentInfo       `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Conf          []byte                 `protobuf:"bytes,2,opt,name=conf,proto3" json:"conf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAgentRequest) GetInfo() *agent.AgentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *CreateAgentRequest) GetConf() []byte {
	if x != nil {
		return x.Conf
	}
	return nil
}

type GetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       []string               `protobuf:"bytes,1,rep,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentStatusRequest) Reset() {
	*x = GetAgentStatusRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentStatusRequest) ProtoMessage() {}

func (x *GetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentStatusRequest) GetAgentId() []string {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type StartGatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGatherRequest) Reset() {
	*x = StartGatherRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGatherRequest) ProtoMessage() {}

func (x *StartGatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGatherRequest.ProtoReflect.Descriptor instead.
func (*StartGatherRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StartGatherRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type StopGatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopGatherRequest) Reset() {
	*x = StopGatherRequest{}
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopGatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopGatherRequest) ProtoMessage() {}

func (x *StopGatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_gateway_api_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopGatherRequest.ProtoReflect.Descriptor instead.
func (*StopGatherRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_gateway_api_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StopGatherRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

var File_protobuf_gateway_api_agent_proto protoreflect.FileDescriptor

var file_protobuf_gateway_api_agent_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x2c, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2e,
	0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x50,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04,
	0x63, 0x6f, 0x6e, 0x66, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x22, 0x7e, 0x0a, 0x10, 0x45, 0x64, 0x69, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c,
	0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x17,
	0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04,
	0x63, 0x6f, 0x6e, 0x66, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x22, 0x58, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74,
	0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x31, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2e, 0x0a,
	0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2d, 0x0a,
	0x11, 0x53, 0x74, 0x6f, 0x70, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x12, 0x5a, 0x10,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protobuf_gateway_api_agent_proto_rawDescOnce sync.Once
	file_protobuf_gateway_api_agent_proto_rawDescData []byte
)

func file_protobuf_gateway_api_agent_proto_rawDescGZIP() []byte {
	file_protobuf_gateway_api_agent_proto_rawDescOnce.Do(func() {
		file_protobuf_gateway_api_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_gateway_api_agent_proto_rawDesc), len(file_protobuf_gateway_api_agent_proto_rawDesc)))
	})
	return file_protobuf_gateway_api_agent_proto_rawDescData
}

var file_protobuf_gateway_api_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protobuf_gateway_api_agent_proto_goTypes = []any{
	(*StartAgentRequest)(nil),     // 0: lubricant.gateway.StartAgentRequest
	(*StopAgentRequest)(nil),      // 1: lubricant.gateway.StopAgentRequest
	(*RemoveAgentRequest)(nil),    // 2: lubricant.gateway.RemoveAgentRequest
	(*UpdateAgentRequest)(nil),    // 3: lubricant.gateway.UpdateAgentRequest
	(*EditAgentRequest)(nil),      // 4: lubricant.gateway.EditAgentRequest
	(*CreateAgentRequest)(nil),    // 5: lubricant.gateway.CreateAgentRequest
	(*GetAgentStatusRequest)(nil), // 6: lubricant.gateway.GetAgentStatusRequest
	(*StartGatherRequest)(nil),    // 7: lubricant.gateway.StartGatherRequest
	(*StopGatherRequest)(nil),     // 8: lubricant.gateway.StopGatherRequest
	(*agent.AgentInfo)(nil),       // 9: lubricant.agent.AgentInfo
}
var file_protobuf_gateway_api_agent_proto_depIdxs = []int32{
	9, // 0: lubricant.gateway.EditAgentRequest.info:type_name -> lubricant.agent.AgentInfo
	9, // 1: lubricant.gateway.CreateAgentRequest.info:type_name -> lubricant.agent.AgentInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_gateway_api_agent_proto_init() }
func file_protobuf_gateway_api_agent_proto_init() {
	if File_protobuf_gateway_api_agent_proto != nil {
		return
	}
	file_protobuf_gateway_api_agent_proto_msgTypes[3].OneofWrappers = []any{}
	file_protobuf_gateway_api_agent_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_gateway_api_agent_proto_rawDesc), len(file_protobuf_gateway_api_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_gateway_api_agent_proto_goTypes,
		DependencyIndexes: file_protobuf_gateway_api_agent_proto_depIdxs,
		MessageInfos:      file_protobuf_gateway_api_agent_proto_msgTypes,
	}.Build()
	File_protobuf_gateway_api_agent_proto = out.File
	file_protobuf_gateway_api_agent_proto_goTypes = nil
	file_protobuf_gateway_api_agent_proto_depIdxs = nil
}
