FROM aenjoy/debian-tdengine-driver:latest AS builder

WORKDIR /app

COPY cmd/apiserver/apiserver ./
RUN chmod +x ./apiserver

FROM aenjoy/debian-tdengine-driver:latest

WORKDIR /
COPY --from=builder /app/apiserver ./

EXPOSE 8080
CMD ["./apiserver"]
