package constant

const (
	ENV_CORE_HOST_STR = "CORE_HOST"
	ENV_CORE_PORT_STR = "CORE_PORT"

	ENV_RUNNING_LEVEL = "RUNNING_LEVEL"

	ENV_CORE_AUTH_PROVIDE          = "AUTH_PROVIDER"
	ENV_CORE_AUTH_ENDPOINT         = "AUTH_ENDPOINT"
	ENV_CORE_AUTH_CLIENT_ID        = "AUTH_CLIENT_ID"
	ENV_CORE_AUTH_CLIENT_SECRET    = "AUTH_CLIENT_SECRET"
	ENV_CORE_AUTH_ORGANIZATION     = "AUTH_ORGANIZATION"
	ENV_CORE_AUTH_PUBLICKEYFILE    = "AUTH_PUBLICKEYFILE"
	ENV_CORE_AUTH_APPLICATION_NAME = "AUTH_APPLICATION_NAME"

	ENV_ENABLE_GRPC_DEBUG_SERVER = "ENABLE_GRPC_DEBUG_SERVER"
	ENV_GRPC_DEBUG_SERVER_PORT   = "GRPC_DEBUG_SERVER_PORT"
	ENV_GATEWAY_USER_ID          = USER_ID
	ENV_GATEWAY_ID_STR           = "GATEWAY_ID"
	ENV_CONF_FILE_ENV            = "CONFIG"
	ENV_HOST                     = "HOST"
	ENV_BIND_GRPC                = "BIND_GRPC"
	ENV_HTTP_LISTEN_PORT_STR     = "HTTP_LISTEN_PORT"
	ENV_LUBRICANT_HOSTNAME_STR   = "HOSTNAME"
)
