FROM alpine:3.21.3 AS builder

WORKDIR /app

COPY cmd/grpcserver/grpcserver ./
RUN chmod +x ./grpcserver

FROM alpine:3.21.3

WORKDIR /
COPY --from=builder /app/grpcserver ./

EXPOSE 5423
CMD ["./grpcserver"]
