FROM alpine:3.21.3 AS builder

WORKDIR /app

COPY cmd/lubricant/lubricant ./
RUN chmod +x ./lubricant

FROM alpine:3.21.3

WORKDIR /
COPY --from=builder /app/lubricant ./

EXPOSE 8080
EXPOSE 5423
CMD ["./lubricant"]
