FROM alpine:3.21.3 AS builder

WORKDIR /app

COPY cmd/reporterHandler/reporterHandler ./
RUN chmod +x ./reporterHandler

FROM alpine:3.21.3

WORKDIR /
COPY --from=builder /app/reporterHandler ./

CMD ["./reporterHandler"]
