// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: protobuf/proxy/api_agent.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	agent "github.com/AEnjoy/IoT-lubricant/protobuf/agent"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId []string `protobuf:"bytes,1,rep,name=agentId,proto3" json:"agentId,omitempty"`
}

func (x *StartAgentRequest) Reset() {
	*x = StartAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proxy_api_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAgentRequest) ProtoMessage() {}

func (x *StartAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proxy_api_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAgentRequest.ProtoReflect.Descriptor instead.
func (*StartAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proxy_api_agent_proto_rawDescGZIP(), []int{0}
}

func (x *StartAgentRequest) GetAgentId() []string {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type StopAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId []string `protobuf:"bytes,1,rep,name=agentId,proto3" json:"agentId,omitempty"`
}

func (x *StopAgentRequest) Reset() {
	*x = StopAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proxy_api_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentRequest) ProtoMessage() {}

func (x *StopAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proxy_api_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentRequest.ProtoReflect.Descriptor instead.
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proxy_api_agent_proto_rawDescGZIP(), []int{1}
}

func (x *StopAgentRequest) GetAgentId() []string {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type RemoveAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId []string `protobuf:"bytes,1,rep,name=agentId,proto3" json:"agentId,omitempty"`
}

func (x *RemoveAgentRequest) Reset() {
	*x = RemoveAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proxy_api_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentRequest) ProtoMessage() {}

func (x *RemoveAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proxy_api_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentRequest.ProtoReflect.Descriptor instead.
func (*RemoveAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proxy_api_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveAgentRequest) GetAgentId() []string {
	if x != nil {
		return x.AgentId
	}
	return nil
}

type UpdateAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Conf    []byte `protobuf:"bytes,2,opt,name=conf,proto3,oneof" json:"conf,omitempty"` //agentCreate config
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proxy_api_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proxy_api_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proxy_api_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateAgentRequest) GetConf() []byte {
	if x != nil {
		return x.Conf
	}
	return nil
}

type EditAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId string           `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Info    *agent.AgentInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Conf    []byte           `protobuf:"bytes,3,opt,name=conf,proto3,oneof" json:"conf,omitempty"` //agentCreate config
}

func (x *EditAgentRequest) Reset() {
	*x = EditAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proxy_api_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAgentRequest) ProtoMessage() {}

func (x *EditAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proxy_api_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAgentRequest.ProtoReflect.Descriptor instead.
func (*EditAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proxy_api_agent_proto_rawDescGZIP(), []int{4}
}

func (x *EditAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EditAgentRequest) GetInfo() *agent.AgentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *EditAgentRequest) GetConf() []byte {
	if x != nil {
		return x.Conf
	}
	return nil
}

type CreateAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *agent.AgentInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Conf []byte           `protobuf:"bytes,2,opt,name=conf,proto3" json:"conf,omitempty"`
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proxy_api_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proxy_api_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proxy_api_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAgentRequest) GetInfo() *agent.AgentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *CreateAgentRequest) GetConf() []byte {
	if x != nil {
		return x.Conf
	}
	return nil
}

var File_protobuf_proxy_api_agent_proto protoreflect.FileDescriptor

var file_protobuf_proxy_api_agent_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x2f, 0x61, 0x70, 0x69, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a,
	0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x10,
	0x53, 0x74, 0x6f, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x12, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x63, 0x6f,
	0x6e, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66,
	0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x7e, 0x0a, 0x10,
	0x45, 0x64, 0x69, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69,
	0x63, 0x61, 0x6e, 0x74, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x04, 0x63, 0x6f,
	0x6e, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66,
	0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x58, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proxy_api_agent_proto_rawDescOnce sync.Once
	file_protobuf_proxy_api_agent_proto_rawDescData = file_protobuf_proxy_api_agent_proto_rawDesc
)

func file_protobuf_proxy_api_agent_proto_rawDescGZIP() []byte {
	file_protobuf_proxy_api_agent_proto_rawDescOnce.Do(func() {
		file_protobuf_proxy_api_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proxy_api_agent_proto_rawDescData)
	})
	return file_protobuf_proxy_api_agent_proto_rawDescData
}

var file_protobuf_proxy_api_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_proxy_api_agent_proto_goTypes = []any{
	(*StartAgentRequest)(nil),  // 0: lubricant.proxy.StartAgentRequest
	(*StopAgentRequest)(nil),   // 1: lubricant.proxy.StopAgentRequest
	(*RemoveAgentRequest)(nil), // 2: lubricant.proxy.RemoveAgentRequest
	(*UpdateAgentRequest)(nil), // 3: lubricant.proxy.UpdateAgentRequest
	(*EditAgentRequest)(nil),   // 4: lubricant.proxy.EditAgentRequest
	(*CreateAgentRequest)(nil), // 5: lubricant.proxy.CreateAgentRequest
	(*agent.AgentInfo)(nil),    // 6: lubricant.agent.AgentInfo
}
var file_protobuf_proxy_api_agent_proto_depIdxs = []int32{
	6, // 0: lubricant.proxy.EditAgentRequest.info:type_name -> lubricant.agent.AgentInfo
	6, // 1: lubricant.proxy.CreateAgentRequest.info:type_name -> lubricant.agent.AgentInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_proxy_api_agent_proto_init() }
func file_protobuf_proxy_api_agent_proto_init() {
	if File_protobuf_proxy_api_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proxy_api_agent_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StartAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proxy_api_agent_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StopAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proxy_api_agent_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proxy_api_agent_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proxy_api_agent_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EditAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proxy_api_agent_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_proxy_api_agent_proto_msgTypes[3].OneofWrappers = []any{}
	file_protobuf_proxy_api_agent_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proxy_api_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_proxy_api_agent_proto_goTypes,
		DependencyIndexes: file_protobuf_proxy_api_agent_proto_depIdxs,
		MessageInfos:      file_protobuf_proxy_api_agent_proto_msgTypes,
	}.Build()
	File_protobuf_proxy_api_agent_proto = out.File
	file_protobuf_proxy_api_agent_proto_rawDesc = nil
	file_protobuf_proxy_api_agent_proto_goTypes = nil
	file_protobuf_proxy_api_agent_proto_depIdxs = nil
}
