// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: protobuf/agent/agent.proto

package agent

import (
	meta "github.com/AEnjoy/IoT-lubricant/protobuf/meta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenapiDocType int32

const (
	OpenapiDocType_originalFile OpenapiDocType = 0
	OpenapiDocType_enableFile   OpenapiDocType = 1
)

// Enum value maps for OpenapiDocType.
var (
	OpenapiDocType_name = map[int32]string{
		0: "originalFile",
		1: "enableFile",
	}
	OpenapiDocType_value = map[string]int32{
		"originalFile": 0,
		"enableFile":   1,
	}
)

func (x OpenapiDocType) Enum() *OpenapiDocType {
	p := new(OpenapiDocType)
	*p = x
	return p
}

func (x OpenapiDocType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenapiDocType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_agent_agent_proto_enumTypes[0].Descriptor()
}

func (OpenapiDocType) Type() protoreflect.EnumType {
	return &file_protobuf_agent_agent_proto_enumTypes[0]
}

func (x OpenapiDocType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenapiDocType.Descriptor instead.
func (OpenapiDocType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{0}
}

type RegisterGatewayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID   string `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	GatewayID string `protobuf:"bytes,2,opt,name=gatewayID,proto3" json:"gatewayID,omitempty"` // 网关ID
}

func (x *RegisterGatewayRequest) Reset() {
	*x = RegisterGatewayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGatewayRequest) ProtoMessage() {}

func (x *RegisterGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGatewayRequest.ProtoReflect.Descriptor instead.
func (*RegisterGatewayRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterGatewayRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *RegisterGatewayRequest) GetGatewayID() string {
	if x != nil {
		return x.GatewayID
	}
	return ""
}

type RegisterGatewayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID string               `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"` // agentID
	Info    *meta.CommonResponse `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *RegisterGatewayResponse) Reset() {
	*x = RegisterGatewayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterGatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGatewayResponse) ProtoMessage() {}

func (x *RegisterGatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGatewayResponse.ProtoReflect.Descriptor instead.
func (*RegisterGatewayResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterGatewayResponse) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *RegisterGatewayResponse) GetInfo() *meta.CommonResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID     string      `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	Description *string     `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	GatewayID   *string     `protobuf:"bytes,3,opt,name=gatewayID,proto3,oneof" json:"gatewayID,omitempty"`
	GatherCycle *int32      `protobuf:"varint,4,opt,name=gatherCycle,proto3,oneof" json:"gatherCycle,omitempty"` // seconds 默认5s
	Algorithm   *string     `protobuf:"bytes,5,opt,name=algorithm,proto3,oneof" json:"algorithm,omitempty"`      //数据压缩算法 默认不压缩
	DataSource  *OpenapiDoc `protobuf:"bytes,6,opt,name=dataSource,proto3,oneof" json:"dataSource,omitempty"`
	Stream      *bool       `protobuf:"varint,7,opt,name=stream,proto3,oneof" json:"stream,omitempty"` // 采集的数据为流式数据，默认为false
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfo) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *AgentInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AgentInfo) GetGatewayID() string {
	if x != nil && x.GatewayID != nil {
		return *x.GatewayID
	}
	return ""
}

func (x *AgentInfo) GetGatherCycle() int32 {
	if x != nil && x.GatherCycle != nil {
		return *x.GatherCycle
	}
	return 0
}

func (x *AgentInfo) GetAlgorithm() string {
	if x != nil && x.Algorithm != nil {
		return *x.Algorithm
	}
	return ""
}

func (x *AgentInfo) GetDataSource() *OpenapiDoc {
	if x != nil {
		return x.DataSource
	}
	return nil
}

func (x *AgentInfo) GetStream() bool {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return false
}

type SetAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID   string     `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	AgentInfo *AgentInfo `protobuf:"bytes,2,opt,name=agentInfo,proto3" json:"agentInfo,omitempty"`
}

func (x *SetAgentRequest) Reset() {
	*x = SetAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentRequest) ProtoMessage() {}

func (x *SetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentRequest.ProtoReflect.Descriptor instead.
func (*SetAgentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SetAgentRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *SetAgentRequest) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

type SetAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *meta.CommonResponse `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SetAgentResponse) Reset() {
	*x = SetAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentResponse) ProtoMessage() {}

func (x *SetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentResponse.ProtoReflect.Descriptor instead.
func (*SetAgentResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SetAgentResponse) GetInfo() *meta.CommonResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

type OpenapiDoc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalFile []byte `protobuf:"bytes,1,opt,name=originalFile,proto3,oneof" json:"originalFile,omitempty"`
	EnableFile   []byte `protobuf:"bytes,2,opt,name=enableFile,proto3,oneof" json:"enableFile,omitempty"`
}

func (x *OpenapiDoc) Reset() {
	*x = OpenapiDoc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenapiDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenapiDoc) ProtoMessage() {}

func (x *OpenapiDoc) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenapiDoc.ProtoReflect.Descriptor instead.
func (*OpenapiDoc) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *OpenapiDoc) GetOriginalFile() []byte {
	if x != nil {
		return x.OriginalFile
	}
	return nil
}

func (x *OpenapiDoc) GetEnableFile() []byte {
	if x != nil {
		return x.EnableFile
	}
	return nil
}

type GetOpenapiDocRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID string         `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	DocType OpenapiDocType `protobuf:"varint,2,opt,name=docType,proto3,enum=lubricant.OpenapiDocType" json:"docType,omitempty"`
}

func (x *GetOpenapiDocRequest) Reset() {
	*x = GetOpenapiDocRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpenapiDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenapiDocRequest) ProtoMessage() {}

func (x *GetOpenapiDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenapiDocRequest.ProtoReflect.Descriptor instead.
func (*GetOpenapiDocRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetOpenapiDocRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *GetOpenapiDocRequest) GetDocType() OpenapiDocType {
	if x != nil {
		return x.DocType
	}
	return OpenapiDocType_originalFile
}

type DataMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID             string               `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	Data                [][]byte             `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	DataLen             int32                `protobuf:"varint,3,opt,name=dataLen,proto3" json:"dataLen,omitempty"`
	DataGatherStartTime string               `protobuf:"bytes,4,opt,name=dataGatherStartTime,proto3" json:"dataGatherStartTime,omitempty"`
	SplitTime           int32                `protobuf:"varint,5,opt,name=splitTime,proto3" json:"splitTime,omitempty"` // 数据分片时间
	Info                *meta.CommonResponse `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *DataMessage) Reset() {
	*x = DataMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMessage) ProtoMessage() {}

func (x *DataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMessage.ProtoReflect.Descriptor instead.
func (*DataMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DataMessage) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *DataMessage) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataMessage) GetDataLen() int32 {
	if x != nil {
		return x.DataLen
	}
	return 0
}

func (x *DataMessage) GetDataGatherStartTime() string {
	if x != nil {
		return x.DataGatherStartTime
	}
	return ""
}

func (x *DataMessage) GetSplitTime() int32 {
	if x != nil {
		return x.SplitTime
	}
	return 0
}

func (x *DataMessage) GetInfo() *meta.CommonResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetAgentInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID string `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
}

func (x *GetAgentInfoRequest) Reset() {
	*x = GetAgentInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoRequest) ProtoMessage() {}

func (x *GetAgentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAgentInfoRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetAgentInfoRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

type GetAgentInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentInfo *AgentInfo           `protobuf:"bytes,1,opt,name=agentInfo,proto3" json:"agentInfo,omitempty"`
	Info      *meta.CommonResponse `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetAgentInfoResponse) Reset() {
	*x = GetAgentInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoResponse) ProtoMessage() {}

func (x *GetAgentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAgentInfoResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentInfoResponse) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

func (x *GetAgentInfoResponse) GetInfo() *meta.CommonResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID string `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *GetDataRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

type SendHttpMethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID string `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method  string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// Types that are assignable to Params:
	//
	//	*SendHttpMethodRequest_Body
	//	*SendHttpMethodRequest_Kv
	Params isSendHttpMethodRequest_Params `protobuf_oneof:"params"`
}

func (x *SendHttpMethodRequest) Reset() {
	*x = SendHttpMethodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHttpMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHttpMethodRequest) ProtoMessage() {}

func (x *SendHttpMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHttpMethodRequest.ProtoReflect.Descriptor instead.
func (*SendHttpMethodRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SendHttpMethodRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *SendHttpMethodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SendHttpMethodRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (m *SendHttpMethodRequest) GetParams() isSendHttpMethodRequest_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (x *SendHttpMethodRequest) GetBody() *RequestBody {
	if x, ok := x.GetParams().(*SendHttpMethodRequest_Body); ok {
		return x.Body
	}
	return nil
}

func (x *SendHttpMethodRequest) GetKv() *meta.KvMap {
	if x, ok := x.GetParams().(*SendHttpMethodRequest_Kv); ok {
		return x.Kv
	}
	return nil
}

type isSendHttpMethodRequest_Params interface {
	isSendHttpMethodRequest_Params()
}

type SendHttpMethodRequest_Body struct {
	Body *RequestBody `protobuf:"bytes,4,opt,name=body,proto3,oneof"`
}

type SendHttpMethodRequest_Kv struct {
	Kv *meta.KvMap `protobuf:"bytes,5,opt,name=kv,proto3,oneof"`
}

func (*SendHttpMethodRequest_Body) isSendHttpMethodRequest_Params() {}

func (*SendHttpMethodRequest_Kv) isSendHttpMethodRequest_Params() {}

type SendHttpMethodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *DataMessage         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Info *meta.CommonResponse `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SendHttpMethodResponse) Reset() {
	*x = SendHttpMethodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendHttpMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendHttpMethodResponse) ProtoMessage() {}

func (x *SendHttpMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendHttpMethodResponse.ProtoReflect.Descriptor instead.
func (*SendHttpMethodResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SendHttpMethodResponse) GetData() *DataMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendHttpMethodResponse) GetInfo() *meta.CommonResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

type RequestBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RequestBody) Reset() {
	*x = RequestBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBody) ProtoMessage() {}

func (x *RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBody.ProtoReflect.Descriptor instead.
func (*RequestBody) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *RequestBody) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type DataChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`    // 每个块数据
	Stamp int32  `protobuf:"varint,2,opt,name=stamp,proto3" json:"stamp,omitempty"` // 时间戳或偏移量
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_agent_agent_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_agent_agent_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_protobuf_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataChunk) GetStamp() int32 {
	if x != nil {
		return x.Stamp
	}
	return 0
}

var File_protobuf_agent_agent_proto protoreflect.FileDescriptor

var file_protobuf_agent_agent_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x75,
	0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x50, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x49, 0x44, 0x22, 0x62, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61,
	0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xe8, 0x02, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12,
	0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x67, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02,
	0x52, 0x0b, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x21, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63,
	0x61, 0x6e, 0x74, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x44, 0x6f, 0x63, 0x48, 0x04,
	0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x49, 0x44, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x67,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x61,
	0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x22, 0x5f, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12,
	0x32, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x41, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e,
	0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x7a, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70,
	0x69, 0x44, 0x6f, 0x63, 0x12, 0x27, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0c, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a,
	0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x01, 0x52, 0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x46,
	0x69, 0x6c, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x22, 0x65, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69,
	0x44, 0x6f, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x12, 0x33, 0x0a, 0x07, 0x64, 0x6f, 0x63, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e,
	0x74, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x44, 0x6f, 0x63, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x07, 0x64, 0x6f, 0x63, 0x54, 0x79, 0x70, 0x65, 0x22, 0xd4, 0x01, 0x0a, 0x0b, 0x44, 0x61,
	0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65,
	0x6e, 0x12, 0x30, 0x0a, 0x13, 0x64, 0x61, 0x74, 0x61, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x64, 0x61, 0x74, 0x61, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x22, 0x2f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x22, 0x79, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c,
	0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2d, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x75,
	0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x2a, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0xb9, 0x01, 0x0a, 0x15, 0x73, 0x65, 0x6e,
	0x64, 0x48, 0x74, 0x74, 0x70, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61,
	0x6e, 0x74, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x22, 0x0a, 0x02, 0x6b, 0x76, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x4b,
	0x76, 0x4d, 0x61, 0x70, 0x48, 0x00, 0x52, 0x02, 0x6b, 0x76, 0x42, 0x08, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x22, 0x73, 0x0a, 0x16, 0x73, 0x65, 0x6e, 0x64, 0x48, 0x74, 0x74, 0x70,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c,
	0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69,
	0x63, 0x61, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x35, 0x0a, 0x09,
	0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2a, 0x32, 0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x44, 0x6f,
	0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x46, 0x69, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x10, 0x01, 0x32, 0xd6, 0x04, 0x0a, 0x0b, 0x65, 0x64, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12,
	0x0f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x1a, 0x0f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x21, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61,
	0x6e, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6c, 0x75, 0x62, 0x72,
	0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x6c, 0x75,
	0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63,
	0x61, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x4f, 0x70, 0x65,
	0x6e, 0x61, 0x70, 0x69, 0x44, 0x6f, 0x63, 0x12, 0x1f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63,
	0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x44, 0x6f,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69,
	0x63, 0x61, 0x6e, 0x74, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x44, 0x6f, 0x63, 0x22,
	0x00, 0x12, 0x51, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1e, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x6c,
	0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63,
	0x61, 0x6e, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x44, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x19, 0x2e, 0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x6c, 0x75, 0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x12, 0x57, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x48,
	0x74, 0x74, 0x70, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x20, 0x2e, 0x6c, 0x75, 0x62, 0x72,
	0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x48, 0x74, 0x74, 0x70, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6c, 0x75,
	0x62, 0x72, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x48, 0x74, 0x74, 0x70,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_agent_agent_proto_rawDescOnce sync.Once
	file_protobuf_agent_agent_proto_rawDescData = file_protobuf_agent_agent_proto_rawDesc
)

func file_protobuf_agent_agent_proto_rawDescGZIP() []byte {
	file_protobuf_agent_agent_proto_rawDescOnce.Do(func() {
		file_protobuf_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_agent_agent_proto_rawDescData)
	})
	return file_protobuf_agent_agent_proto_rawDescData
}

var file_protobuf_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protobuf_agent_agent_proto_goTypes = []any{
	(OpenapiDocType)(0),             // 0: lubricant.OpenapiDocType
	(*RegisterGatewayRequest)(nil),  // 1: lubricant.RegisterGatewayRequest
	(*RegisterGatewayResponse)(nil), // 2: lubricant.RegisterGatewayResponse
	(*AgentInfo)(nil),               // 3: lubricant.AgentInfo
	(*SetAgentRequest)(nil),         // 4: lubricant.SetAgentRequest
	(*SetAgentResponse)(nil),        // 5: lubricant.SetAgentResponse
	(*OpenapiDoc)(nil),              // 6: lubricant.openapiDoc
	(*GetOpenapiDocRequest)(nil),    // 7: lubricant.GetOpenapiDocRequest
	(*DataMessage)(nil),             // 8: lubricant.DataMessage
	(*GetAgentInfoRequest)(nil),     // 9: lubricant.GetAgentInfoRequest
	(*GetAgentInfoResponse)(nil),    // 10: lubricant.GetAgentInfoResponse
	(*GetDataRequest)(nil),          // 11: lubricant.GetDataRequest
	(*SendHttpMethodRequest)(nil),   // 12: lubricant.sendHttpMethodRequest
	(*SendHttpMethodResponse)(nil),  // 13: lubricant.sendHttpMethodResponse
	(*RequestBody)(nil),             // 14: lubricant.requestBody
	(*DataChunk)(nil),               // 15: lubricant.dataChunk
	(*meta.CommonResponse)(nil),     // 16: lubricant.CommonResponse
	(*meta.KvMap)(nil),              // 17: lubricant.KvMap
	(*meta.Ping)(nil),               // 18: lubricant.Ping
}
var file_protobuf_agent_agent_proto_depIdxs = []int32{
	16, // 0: lubricant.RegisterGatewayResponse.info:type_name -> lubricant.CommonResponse
	6,  // 1: lubricant.AgentInfo.dataSource:type_name -> lubricant.openapiDoc
	3,  // 2: lubricant.SetAgentRequest.agentInfo:type_name -> lubricant.AgentInfo
	16, // 3: lubricant.SetAgentResponse.info:type_name -> lubricant.CommonResponse
	0,  // 4: lubricant.GetOpenapiDocRequest.docType:type_name -> lubricant.OpenapiDocType
	16, // 5: lubricant.DataMessage.info:type_name -> lubricant.CommonResponse
	3,  // 6: lubricant.GetAgentInfoResponse.agentInfo:type_name -> lubricant.AgentInfo
	16, // 7: lubricant.GetAgentInfoResponse.info:type_name -> lubricant.CommonResponse
	14, // 8: lubricant.sendHttpMethodRequest.body:type_name -> lubricant.requestBody
	17, // 9: lubricant.sendHttpMethodRequest.kv:type_name -> lubricant.KvMap
	8,  // 10: lubricant.sendHttpMethodResponse.data:type_name -> lubricant.DataMessage
	16, // 11: lubricant.sendHttpMethodResponse.info:type_name -> lubricant.CommonResponse
	18, // 12: lubricant.edgeService.ping:input_type -> lubricant.Ping
	1,  // 13: lubricant.edgeService.registerGateway:input_type -> lubricant.RegisterGatewayRequest
	4,  // 14: lubricant.edgeService.setAgent:input_type -> lubricant.SetAgentRequest
	7,  // 15: lubricant.edgeService.getOpenapiDoc:input_type -> lubricant.GetOpenapiDocRequest
	9,  // 16: lubricant.edgeService.getAgentInfo:input_type -> lubricant.GetAgentInfoRequest
	11, // 17: lubricant.edgeService.data:input_type -> lubricant.GetDataRequest
	11, // 18: lubricant.edgeService.GetDataStream:input_type -> lubricant.GetDataRequest
	12, // 19: lubricant.edgeService.sendHttpMethod:input_type -> lubricant.sendHttpMethodRequest
	18, // 20: lubricant.edgeService.ping:output_type -> lubricant.Ping
	2,  // 21: lubricant.edgeService.registerGateway:output_type -> lubricant.RegisterGatewayResponse
	5,  // 22: lubricant.edgeService.setAgent:output_type -> lubricant.SetAgentResponse
	6,  // 23: lubricant.edgeService.getOpenapiDoc:output_type -> lubricant.openapiDoc
	10, // 24: lubricant.edgeService.getAgentInfo:output_type -> lubricant.GetAgentInfoResponse
	8,  // 25: lubricant.edgeService.data:output_type -> lubricant.DataMessage
	15, // 26: lubricant.edgeService.GetDataStream:output_type -> lubricant.dataChunk
	13, // 27: lubricant.edgeService.sendHttpMethod:output_type -> lubricant.sendHttpMethodResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protobuf_agent_agent_proto_init() }
func file_protobuf_agent_agent_proto_init() {
	if File_protobuf_agent_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_agent_agent_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterGatewayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterGatewayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SetAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OpenapiDoc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetOpenapiDocRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DataMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetAgentInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetAgentInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SendHttpMethodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SendHttpMethodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RequestBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_agent_agent_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*DataChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_agent_agent_proto_msgTypes[2].OneofWrappers = []any{}
	file_protobuf_agent_agent_proto_msgTypes[5].OneofWrappers = []any{}
	file_protobuf_agent_agent_proto_msgTypes[11].OneofWrappers = []any{
		(*SendHttpMethodRequest_Body)(nil),
		(*SendHttpMethodRequest_Kv)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_agent_agent_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_agent_agent_proto_goTypes,
		DependencyIndexes: file_protobuf_agent_agent_proto_depIdxs,
		EnumInfos:         file_protobuf_agent_agent_proto_enumTypes,
		MessageInfos:      file_protobuf_agent_agent_proto_msgTypes,
	}.Build()
	File_protobuf_agent_agent_proto = out.File
	file_protobuf_agent_agent_proto_rawDesc = nil
	file_protobuf_agent_agent_proto_goTypes = nil
	file_protobuf_agent_agent_proto_depIdxs = nil
}
