// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: protobuf/agent/agent.proto

package agent

import (
	context "context"
	meta "github.com/AEnjoy/IoT-lubricant/protobuf/meta"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdgeService_Ping_FullMethodName            = "/lubricant.edgeService/ping"
	EdgeService_RegisterGateway_FullMethodName = "/lubricant.edgeService/registerGateway"
	EdgeService_SetAgent_FullMethodName        = "/lubricant.edgeService/setAgent"
	EdgeService_GetOpenapiDoc_FullMethodName   = "/lubricant.edgeService/getOpenapiDoc"
	EdgeService_GetAgentInfo_FullMethodName    = "/lubricant.edgeService/getAgentInfo"
	EdgeService_Data_FullMethodName            = "/lubricant.edgeService/data"
	EdgeService_GetDataStream_FullMethodName   = "/lubricant.edgeService/GetDataStream"
	EdgeService_SendHttpMethod_FullMethodName  = "/lubricant.edgeService/sendHttpMethod"
)

// EdgeServiceClient is the client API for EdgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdgeServiceClient interface {
	Ping(ctx context.Context, in *meta.Ping, opts ...grpc.CallOption) (*meta.Ping, error)
	RegisterGateway(ctx context.Context, in *RegisterGatewayRequest, opts ...grpc.CallOption) (*RegisterGatewayResponse, error)
	SetAgent(ctx context.Context, in *SetAgentRequest, opts ...grpc.CallOption) (*SetAgentResponse, error)
	GetOpenapiDoc(ctx context.Context, in *GetOpenapiDocRequest, opts ...grpc.CallOption) (*OpenapiDoc, error)
	GetAgentInfo(ctx context.Context, in *GetAgentInfoRequest, opts ...grpc.CallOption) (*GetAgentInfoResponse, error)
	Data(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*DataMessage, error)
	GetDataStream(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	SendHttpMethod(ctx context.Context, in *SendHttpMethodRequest, opts ...grpc.CallOption) (*SendHttpMethodResponse, error)
}

type edgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeServiceClient(cc grpc.ClientConnInterface) EdgeServiceClient {
	return &edgeServiceClient{cc}
}

func (c *edgeServiceClient) Ping(ctx context.Context, in *meta.Ping, opts ...grpc.CallOption) (*meta.Ping, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(meta.Ping)
	err := c.cc.Invoke(ctx, EdgeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeServiceClient) RegisterGateway(ctx context.Context, in *RegisterGatewayRequest, opts ...grpc.CallOption) (*RegisterGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterGatewayResponse)
	err := c.cc.Invoke(ctx, EdgeService_RegisterGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeServiceClient) SetAgent(ctx context.Context, in *SetAgentRequest, opts ...grpc.CallOption) (*SetAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAgentResponse)
	err := c.cc.Invoke(ctx, EdgeService_SetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeServiceClient) GetOpenapiDoc(ctx context.Context, in *GetOpenapiDocRequest, opts ...grpc.CallOption) (*OpenapiDoc, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenapiDoc)
	err := c.cc.Invoke(ctx, EdgeService_GetOpenapiDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeServiceClient) GetAgentInfo(ctx context.Context, in *GetAgentInfoRequest, opts ...grpc.CallOption) (*GetAgentInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentInfoResponse)
	err := c.cc.Invoke(ctx, EdgeService_GetAgentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeServiceClient) Data(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*DataMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataMessage)
	err := c.cc.Invoke(ctx, EdgeService_Data_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeServiceClient) GetDataStream(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EdgeService_ServiceDesc.Streams[0], EdgeService_GetDataStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDataRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeService_GetDataStreamClient = grpc.ServerStreamingClient[DataChunk]

func (c *edgeServiceClient) SendHttpMethod(ctx context.Context, in *SendHttpMethodRequest, opts ...grpc.CallOption) (*SendHttpMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendHttpMethodResponse)
	err := c.cc.Invoke(ctx, EdgeService_SendHttpMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeServiceServer is the server API for EdgeService service.
// All implementations must embed UnimplementedEdgeServiceServer
// for forward compatibility.
type EdgeServiceServer interface {
	Ping(context.Context, *meta.Ping) (*meta.Ping, error)
	RegisterGateway(context.Context, *RegisterGatewayRequest) (*RegisterGatewayResponse, error)
	SetAgent(context.Context, *SetAgentRequest) (*SetAgentResponse, error)
	GetOpenapiDoc(context.Context, *GetOpenapiDocRequest) (*OpenapiDoc, error)
	GetAgentInfo(context.Context, *GetAgentInfoRequest) (*GetAgentInfoResponse, error)
	Data(context.Context, *GetDataRequest) (*DataMessage, error)
	GetDataStream(*GetDataRequest, grpc.ServerStreamingServer[DataChunk]) error
	SendHttpMethod(context.Context, *SendHttpMethodRequest) (*SendHttpMethodResponse, error)
	mustEmbedUnimplementedEdgeServiceServer()
}

// UnimplementedEdgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeServiceServer struct{}

func (UnimplementedEdgeServiceServer) Ping(context.Context, *meta.Ping) (*meta.Ping, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEdgeServiceServer) RegisterGateway(context.Context, *RegisterGatewayRequest) (*RegisterGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGateway not implemented")
}
func (UnimplementedEdgeServiceServer) SetAgent(context.Context, *SetAgentRequest) (*SetAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAgent not implemented")
}
func (UnimplementedEdgeServiceServer) GetOpenapiDoc(context.Context, *GetOpenapiDocRequest) (*OpenapiDoc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpenapiDoc not implemented")
}
func (UnimplementedEdgeServiceServer) GetAgentInfo(context.Context, *GetAgentInfoRequest) (*GetAgentInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentInfo not implemented")
}
func (UnimplementedEdgeServiceServer) Data(context.Context, *GetDataRequest) (*DataMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Data not implemented")
}
func (UnimplementedEdgeServiceServer) GetDataStream(*GetDataRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetDataStream not implemented")
}
func (UnimplementedEdgeServiceServer) SendHttpMethod(context.Context, *SendHttpMethodRequest) (*SendHttpMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHttpMethod not implemented")
}
func (UnimplementedEdgeServiceServer) mustEmbedUnimplementedEdgeServiceServer() {}
func (UnimplementedEdgeServiceServer) testEmbeddedByValue()                     {}

// UnsafeEdgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeServiceServer will
// result in compilation errors.
type UnsafeEdgeServiceServer interface {
	mustEmbedUnimplementedEdgeServiceServer()
}

func RegisterEdgeServiceServer(s grpc.ServiceRegistrar, srv EdgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedEdgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeService_ServiceDesc, srv)
}

func _EdgeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(meta.Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceServer).Ping(ctx, req.(*meta.Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeService_RegisterGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceServer).RegisterGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeService_RegisterGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceServer).RegisterGateway(ctx, req.(*RegisterGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeService_SetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceServer).SetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeService_SetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceServer).SetAgent(ctx, req.(*SetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeService_GetOpenapiDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenapiDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceServer).GetOpenapiDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeService_GetOpenapiDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceServer).GetOpenapiDoc(ctx, req.(*GetOpenapiDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeService_GetAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceServer).GetAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeService_GetAgentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceServer).GetAgentInfo(ctx, req.(*GetAgentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeService_Data_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceServer).Data(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeService_Data_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceServer).Data(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeService_GetDataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EdgeServiceServer).GetDataStream(m, &grpc.GenericServerStream[GetDataRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeService_GetDataStreamServer = grpc.ServerStreamingServer[DataChunk]

func _EdgeService_SendHttpMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendHttpMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeServiceServer).SendHttpMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeService_SendHttpMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeServiceServer).SendHttpMethod(ctx, req.(*SendHttpMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeService_ServiceDesc is the grpc.ServiceDesc for EdgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lubricant.edgeService",
	HandlerType: (*EdgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ping",
			Handler:    _EdgeService_Ping_Handler,
		},
		{
			MethodName: "registerGateway",
			Handler:    _EdgeService_RegisterGateway_Handler,
		},
		{
			MethodName: "setAgent",
			Handler:    _EdgeService_SetAgent_Handler,
		},
		{
			MethodName: "getOpenapiDoc",
			Handler:    _EdgeService_GetOpenapiDoc_Handler,
		},
		{
			MethodName: "getAgentInfo",
			Handler:    _EdgeService_GetAgentInfo_Handler,
		},
		{
			MethodName: "data",
			Handler:    _EdgeService_Data_Handler,
		},
		{
			MethodName: "sendHttpMethod",
			Handler:    _EdgeService_SendHttpMethod_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDataStream",
			Handler:       _EdgeService_GetDataStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/agent/agent.proto",
}
