FROM alpine:3.21.3 AS builder

WORKDIR /app

COPY cmd/gateway/gateway ./
RUN chmod +x ./gateway

FROM aenjoy/debian-tdengine-driver:latest
WORKDIR /root/
RUN apt-get update && apt-get install -y libzstd1 && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/gateway ./

CMD ["./gateway"]
