apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tdengine
  namespace: database
spec:
  serviceName: tdengine-service
  replicas: 2
  selector:
    matchLabels:
      app: tdengine
  template:
    metadata:
      labels:
        app: tdengine
    spec:
      containers:
        - name: tdengine
          image: tdengine/tdengine:3.3.5.2 # TDEngineDriver 对版本有严格要求，只有前三位一致才能使用 https://docs.taosdata.com/train-faq/faq/#26-%E9%81%87%E5%88%B0%E6%8A%A5%E9%94%99-dnd-error-version-not-compatible-client-3000700-server-3020300
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TAOS_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tsdatabase-secret
                  key: root-password
          command:
            - "/bin/sh"
            - "-c"
            - |
              export TAOS_FQDN=${POD_NAME}.tdengine-service.database.svc.cluster.local
              exec taosd
          ports:
            - containerPort: 6030
              name: client
            - containerPort: 6035
              name: rest
            - containerPort: 6041
              name: cluster
          volumeMounts:
            - name: taosdata
              mountPath: /var/lib/taos
      volumes:
        - name: taosdata
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tdengine
  namespace: database
spec:
  clusterIP: None
  ports:
    - name: client
      port: 6030
      targetPort: 6030
    - name: rest
      port: 6035
      targetPort: 6035
    - name: cluster
      port: 6041
      targetPort: 6041
  selector:
    app: tdengine
