# nonk8s
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.32.2
    extraMounts:
      - hostPath: /etc/casdoor
        containerPath: /etc/casdoor
    extraPortMappings:
      - containerPort: 80
        hostPort: 30080
      - containerPort: 443
        hostPort: 30443
