apiVersion: v1
kind: Namespace
metadata:
  name: auth-core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor
  namespace: auth-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor-container
          image: casbin/casdoor:v1.854.0
          ports:
            - containerPort: 8000
          env:
            - name: driverName
              value: "mysql"
            - name: dataSourceName
              value: "casdoor:123456@tcp(mysql.database.svc.cluster.local:3306)/"
            - name: redisEndpoint
              value: "redis.database.svc.cluster.local:6379,3,123456"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: casdoor-service
  namespace: auth-core
spec:
  selector:
    app: casdoor
  ports:
    - protocol: TCP
      name: http-map
      port: 8000
      targetPort: 8000
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
  type: NodePort
