apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubricant-agent
  namespace: lubricant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lubricant-agent
  template:
    metadata:
      labels:
        app: lubricant-agent
    spec:
      containers:
        - name: lubricant-agent
          image: hub.iotroom.top/aenjoy/lubricant-agent:nightly
          ports:
            - containerPort: 5436
              name: grpc
              protocol: TCP
              hostPort: 5436
          env:
            - name: BIND_GRPC
              value: "0.0.0.0:5436"
          readinessProbe:
            tcpSocket:
              port: 5436
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: lubricant-agent
  namespace: lubricant
spec:
  ports:
    - port: 5436
      name: grpc
      targetPort: 5436
  selector:
    app: lubricant-agent
