apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lubricant-agent
  namespace: lubricant
spec:
  serviceName: "lubricant-agent"
  replicas: 1
  selector:
    matchLabels:
      app: lubricant-agent
  template:
    metadata:
      labels:
        app: lubricant-agent
    spec:
      containers:
        - name: lubricant-agent
          image: hub.iotroom.top/aenjoy/lubricant-agent:nightly
          ports:
            - containerPort: 5436
              name: grpc
              protocol: TCP
          env:
            - name: BIND_GRPC
              value: "0.0.0.0:5436"
          readinessProbe:
            tcpSocket:
              port: 5436
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
