# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: End-to-End Test (RunningAtContainer)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: E2E Test Agent
        run: |
          set -e
          make build-agent
          docker run -itd --net=host hub.iotroom.top/AEnjoy/lubricant-agent:nightly
          go build -o test/agent_test ./cmd/test/agent
          # python3 test/files/util_modify_api_url.py
          cd test
          ./agent_test mini --agent-id clock-agent 
          cd ..
