name: Kubernetes CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Prepare Files
        run: |
          set -e
          scripts/casdoor_init.sh

      - uses: engineerd/setup-kind@v0.6.0
        with:
          version: v0.24.0
          config: scripts/kind.yaml

      - name: Verify Kubernetes cluster
        run: |
          kubectl cluster-info
          kubectl version

      - name: Build And Load Containers To Kubernetes
        run: |
          set -e
          make load-to-kind

      - name: Prepare Kubernetes Environment
        run: |
          set -e
          kubectl run nginx --image=nginx:1.25
          bash deployment/infra/db/redis.sh
          bash deployment/infra/db/deploy-mysql.sh
          bash deployment/infra/auth/casdoor.sh
          bash scripts/push_files_to_nginx_pod.sh
          kubectl exec nginx -- 'cd /root/k8s && bash ./casdoor_init.sh'
          mkdir -p /etc/casdoor
          echo $(kubectl exec nginx -- cat /root/k8s/crt.pem) > /etc/casdoor/public.pem

      - name: Deploy Lubricant
        run: |
          set -e 
          bash deployment/infra/secret.sh
          kubectl apply -f deployment/infra/lubricant-core.yaml
