# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.22','1.23', '1.24' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: UnitTest
      run: |
        set -e
        make test

#    - name: Build
#      run: go build -v ./...
